In [ ]:
import numpy as np

# 定義係數矩陣 A 和常數項向量 b
A = np.array([
    [ 4, -1,  0, -1,  0,  0],
    [-1,  4, -1,  0, -1,  0],
    [ 0, -1,  4,  0,  1, -1],
    [-1,  0,  0,  4, -1, -1],
    [ 0, -1,  0, -1,  4, -1],
    [ 0,  0, -1,  0, -1,  4]
], dtype=float)

b = np.array([0, -1, 9, 4, 8, 6], dtype=float)

# 收斂條件
tolerance = 1e-10
max_iterations = 1000

# Jacobi method
def jacobi(A, b, x0):
    x = x0.copy()
    D = np.diag(A)
    R = A - np.diagflat(D)
    for _ in range(max_iterations):
        x_new = (b - np.dot(R, x)) / D
        if np.linalg.norm(x_new - x, ord=np.inf) < tolerance:
            return x_new
        x = x_new
    return x

# Gauss-Seidel method
def gauss_seidel(A, b, x0):
    x = x0.copy()
    n = len(b)
    for _ in range(max_iterations):
        x_new = x.copy()
        for i in range(n):
            s1 = np.dot(A[i, :i], x_new[:i])
            s2 = np.dot(A[i, i + 1:], x[i + 1:])
            x_new[i] = (b[i] - s1 - s2) / A[i, i]
        if np.linalg.norm(x_new - x, ord=np.inf) < tolerance:
            return x_new
        x = x_new
    return x

# SOR method
def sor(A, b, x0, omega=1.25):
    x = x0.copy()
    n = len(b)
    for _ in range(max_iterations):
        x_new = x.copy()
        for i in range(n):
            s1 = np.dot(A[i, :i], x_new[:i])
            s2 = np.dot(A[i, i + 1:], x[i + 1:])
            x_new[i] = (1 - omega) * x[i] + (omega / A[i, i]) * (b[i] - s1 - s2)
        if np.linalg.norm(x_new - x, ord=np.inf) < tolerance:
            return x_new
        x = x_new
    return x

# Conjugate Gradient method
def conjugate_gradient(A, b, x0):
    x = x0.copy()
    r = b - np.dot(A, x)
    p = r.copy()
    rs_old = np.dot(r, r)
    for _ in range(max_iterations):
        Ap = np.dot(A, p)
        alpha = rs_old / np.dot(p, Ap)
        x += alpha * p
        r -= alpha * Ap
        rs_new = np.dot(r, r)
        if np.sqrt(rs_new) < tolerance:
            return x
        p = r + (rs_new / rs_old) * p
        rs_old = rs_new
    return x

# 初始猜測值
x0 = np.zeros_like(b)

# 執行四種方法
x_jacobi = jacobi(A, b, x0)
x_gs = gauss_seidel(A, b, x0)
x_sor = sor(A, b, x0, omega=1.25)
x_cg = conjugate_gradient(A, b, x0)

# 印出結果
print("Jacobi method:\n", x_jacobi)
print("Gauss-Seidel method:\n", x_gs)
print("SOR method:\n", x_sor)
print("Conjugate Gradient method:\n", x_cg)


Jacobi method:
 [1.31614827 2.02854708 3.61951427 3.23604602 4.17852578 3.44951001]
Gauss-Seidel method:
 [1.31614827 2.02854708 3.61951427 3.23604602 4.17852578 3.44951001]
SOR method:
 [1.31614827 2.02854708 3.61951427 3.23604602 4.17852578 3.44951001]
Conjugate Gradient method:
 [1.31614827 2.02854708 3.61951427 3.23604602 4.17852578 3.44951001]
